### ISSUE TITLE
event OnPlayerGlobalVariableChanged doesn't seem to work

### ISSUE THREAD

**Issue by db0** [octgn/OCTGN#1491] opened 2015-07-13 21:57 UTC
I just tried to use this event in API 3.1.0.1 and it doesn't seem to trigger at all. ```OnGlobalVariableChanged``` works fine.

**Comment by brine** [comment] 2015-07-13 22:00
I don't think it triggers locally, some of the events I've noticed only trigger for the other players

**Comment by db0** [comment] 2015-07-13 22:01
That's weird. Makes things more complicated...

**Comment by brine** [comment] 2015-07-13 22:16
I'm open to expand and change the trigger mechanisms for the events but they probably won't be exposed to the older API versions

**Comment by brine** [comment] 2015-07-13 22:17
but now's the time to put together what you want to see changed/fixed in the API cuz the next one should be rolled out soon

**Comment by db0** [comment] 2015-07-13 22:21
I think making this even trigger from the local player would make sense given that ```OnGlobalVariableChanged``` also triggers from the local player, and it makes little sense to be a disconnect between them

**Comment by db0** [comment] 2015-07-13 22:29
update: Tested in multiplayer. Event doesn't trigger even for remote players.

**Comment by brine** [comment] 2015-07-13 23:10
https://github.com/octgn/OCTGN/blob/master/octgnFX/Octgn/Networking/ClientHandler.cs#L935

``if (p != Player.LocalPlayer)``

yeah there's an intentional restriction to not trigger the event locally.  I believe this was by design as it does this on several other events as well.

I can lift the restrictions across the entire event system, but I have a feeling that script processing overload was part of the reason this was done in the first place.

**Closed** 2015-08-12 20:08 UTC
