### ISSUE TITLE
cardDlg need more cardstatus

### ISSUE THREAD

**Issue by fatelesscn** [octgn/OCTGN#1549] opened 2016-01-14 13:37 UTC
i want to display card info(such as highlight, markers etc)in carddlg, for same cards on board may have different card info(such as highlight, markers etc),and players will need to know these info when they are trying to choose the right card.
Such as this situation
![q1] (http://upload.ouliu.net/i/20160114213938oycra.jpeg)

**Comment by brine** [comment] 2016-01-14 16:33
Why do you need to use the dialog for cards already on the table? The table itself is already a big card dlg window, just make a cardaction to select the card you want

**Comment by brine** [comment] 2016-01-14 16:35
Also, duplicate of https://github.com/octgn/OCTGN/issues/1298 (API call name changed but function is the same)

**Closed by brine** 2016-01-14 16:35 UTC
