### ISSUE TITLE
o8build console

### ISSUE THREAD

**Issue by Roghka** [octgn/OCTGN#1832] opened 2019-02-12 05:10 UTC
If definition.xml have some mistakes o8build.exe console just insta closes and O8buildgui doesnt says anything about errors. Wtf, its just hard to make console doesnt close on error, to see what erorr is it, or write some log file?
Console.Read() // does you hear about this?

**Comment by Gravecorp** [comment] 2019-02-12 08:38
Yes i am sorry its very difficult to open it from a command prompt which will show you the error output. Also for us to fix this issue it helps if we have some idea of the version of octgn you are using and some way to reproduce the error.

**Comment by kellyelton** [comment] 2019-02-13 00:02
o8build was designed like that on purpose, it's not an interactive program.

o8buildgui should also display errors.

Can you verify that o8build is showing errors, but o8buildgui is not?

**Comment by brine** [comment] 2019-02-27 18:05
there were issues with o8buildgui failing because it couldn't locate the o8build exe.  Mainly since it was missing from previous installers.  I believe this was the cause of the GUI failng, and it should be fixed now.  If there are further issues with the GUI, please let us know and it will be reopened.

**Closed** 2019-02-27 18:05 UTC
Labels: Needs Reproduction, Under Investigation
