### ISSUE TITLE
Feature Request: Skip checking for updates when offline

### ISSUE THREAD

**Issue by talex9** [octgn/OCTGN#1883] opened 2019-07-04 04:32 UTC
I've noticed that when the client starts, but no connection is available, it takes a considerable amount of time checking for updates on each game. it even does so more than when actual updates are needed, so I reached the conclusion that maybe a re-connection check is being done a number of times before moving on.

But the actual problem comes when checking all games! since it seems that re-connection check is done for each one, the time it takes for me to open a single client becomes rather large.

The feature I propose is for a skip on checks or a skip when offline mode is detected. hopefully it'd be something attendable. gratitude in advance.

**Comment by talex9** [comment] 2019-07-04 04:44
Great! high hopes and fingers crossed!! :dancer:

**Comment by BenMatteson** [comment] 2019-07-08 17:28
This is actually not the case, if the system is actually offline it will skip any checking for updates, it is only when it is able to reach the internet, but there is some issue with the connection to the server providing the games that this comes up. 
In regards to that very real problem, this is actually a duplicate of #1228

**Closed by BenMatteson** 2019-07-08 17:28 UTC
Labels: Feature Request, Planned
